services:
  frontend-1:
    build: ./first-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - frontend-network
  
  frontend-2:
    build: ./second-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - frontend-network

  frontend-3:
    build: ./third-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=4200
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true
    name: frontend-network