
server {
    listen 80;
    server_name _;

    
    location / {
        proxy_set_header Host localhost;    
        proxy_pass http://frontend-1:3000/;
    }

    location /2/ {
        proxy_pass http://frontend-2:4200/;
    }

    location /3/ {
        proxy_set_header Host localhost;
        proxy_pass http://frontend-3:4201/;
    }
    
    location /api/1/ {
        proxy_set_header Host localhost;        
        proxy_pass http://backend-1:3001/;
    }
    
    location /api/2/ {
        proxy_set_header Host localhost;    
        proxy_pass http://backend-2:3002/;
    }
}