
server {
    listen 80;
    server_name _;

    
    location /1 {
        proxy_set_header Host $host;
        proxy_pass http://frontend-1:3000;
    }

    location /1/ {
        proxy_set_header Host $host;
        proxy_pass http://frontend-1:3000;
    }

    location /2 {
        return 301 /2/;
    }

    location /2/ {
        proxy_pass http://frontend-2:4000;
    }

    location /3 {
        return 301 /3/;
    }

    location /3/ {
        proxy_set_header Host localhost;
        proxy_pass http://frontend-3:4200;
    }
    
    location /api/1/ {
        proxy_set_header Host localhost;        
        proxy_pass http://backend-1:3001/;
    }
    
    location /api/2/ {
        proxy_set_header Host localhost;    
        proxy_pass http://backend-2:3002/;
    }
}