name: My First Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello from GitHub Actions!"

      - name: Current directory
        run: pwd
      
      - name: Check directory contents
        run: ls -la
  
      - name: Up Networks
        run: ./networks.sh

      - name: Up containers
        run: ./up.sh