name: My First Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello from GitHub Actions!"

      - name: Current directory
        run: pwd
      
      - name: Check directory contents
        run: ls -la

      - name: Check Docker version
        run: docker --version
  
      - name: Up Networks
        run: ./networks.sh

      - name: Build Infrastructure
        run: docker compose build
        working-directory: Infrastructure
      
      - name: Build Backend
        run: docker compose build
        working-directory: Application/backend
      
      - name: Build Frontend
        run: docker compose build
        working-directory: Application/frontend
      
      - name: Build Gateway
        run: docker compose build
        working-directory: Gateway