name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_MY }}

      - name: Docker version
        run: docker --version

      - name: Docker Compose version
        run: docker compose version

      - name: Network create
        run: docker network create frontend-network || true && docker network create backend-network || true && docker network create infrastructure-network || true

      - name: Network Check
        run: docker network ls

      - name: Build Infrastructure
        working-directory: Infrastructure
        run: docker compose build

      - name: Build Backend
        working-directory: Application/backend
        run: docker compose build

      - name: Build Frontend
        working-directory: Application/frontend
        run: docker compose build

      - name: Build Gateway
        working-directory: Gateway
        run: docker compose build